channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - pip
  - pip:
      - transformers --upgrade
      - pydantic==1.9.1
      - gpustat --force-reinstall
      - azure-keyvault-secrets
      - azure-core --upgrade
      - pandas
      - ray
name: testenv
